# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Diego Manzanas Lopez
tagline:          'website'
description:      'My personal website.'
url:              http://dieman95.github.io
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Diego Manzanas Lopez
  url:            https://google.com/+IanCamporezBrunelli

paginate:         5

# Custom vars
icon:             /assets/images/icon_sa.svg
cover:            /assets/images/cover.jpg

social:
  - icon:         twitter
    url:          https://twitter.com/dieman95
    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/dieman95
    desc:         Find me on github

  - icon:         google
    url:          https://scholar.google.com/citations?user=kgpZCIAAAAAJ&hl=en
    desc:         Follow my work

  - icon:         linkedin
    url:          https://www.linkedin.com/in/diego-manzanas-lopez/
    desc:         Follow me on linkedin

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about
    
  - title:        CV
    url:          /cv
    
  - title:        Projects
    url:          /projects

copyright:
  author:         Camporez
  url:            http://camporez.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
